#!/bin/sh

VERSION="0.2"
COPYRIGHT_YEARS="2015"

# linkdup - create links between duplicate files
#
# Copyright (C) 2015 Joao Eriberto Mota Filho <eriberto@debian.org>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 3. Neither the name of the author nor the names of its contributors
#    may be used to endorse or promote products derived from this software
#    without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.

#############################
### Function to show the help
#############################

usage() {
cat << EOT

linkdup - create links between duplicate files

Usage: linkdup [-h|--help] [-V] [-v] [-r] [-s|-S] [-2] -d DIRECTORY

  -h, --help    Show this help.
  -V            Show version.
  -v            Verbose. Works with -s or -S only.
  -r            Recursive.
  -s            Create relative symlinks. Do not use with -S.
  -S            Create absolute symlinks. Do not use with -s.
  -2            Use SHA256 hash instead of MD5 (MD5 is default, is faster).
  -l SIZE       The max file size used in search. Can be used pure bytes or
                'k' for kilobyte, 'm' for megabytes and 'g' for gigabytes.
  -d DIRECTORY  Directory to be inspected. This option is MANDATORY.

Without the -s or -S options, linkdup will only show the duplicate files.

Example: linkdup -r -s -d /test

EOT
}


#######################################
### Function to remove any old tmp file
#######################################

tmpremove() {
    find /tmp -maxdepth 1 -type f -name 'linkdup-[0-9]*' -exec rm -f {} \;
}


############################
### Function to create links
############################

makelinks() {
    MAINFILE=$(head -n 1 $FILE | tr -s " " | cut -d" " -f2)

    for TARGET in $(tail -n +2 $FILE | tr -s " " | cut -d" " -f2)
    do
      ln $OPTIONS $VERBOSE $MAINFILE $TARGET
    done
}


############################
### Function to show version
############################

showversion() {
cat << EOT

linkdup $VERSION
Copyright (C) $COPYRIGHT_YEARS Joao Eriberto Mota Filho <eriberto@debian.org>

This code is under BSD-3-Clause license.

EOT
}


#############
### Variables
#############

ASYMLINK=0
DIRECTORY=""
HASH="md5sum"
MAXDEPTH=1
OPTIONS=""
PATH=/usr/sbin:/usr/bin:/sbin:/bin
SIZECONTROL=0
SYMLINK=0
TMPFILE=/tmp/linkdup-$(date '+%s')
VERBOSE=0


#############################
### First check - valid args?
#############################

# A good practice
tmpremove

# The options check
while getopts VvrsS2d: OPT
do
    case $OPT in
    V) showversion; exit;;
    v) VERBOSE="-v";;
    r) MAXDEPTH=1000;;
    s) SYMLINK=1;;
    S) ASYMLINK=1;;
    2) HASH="sha256sum";;
    l) SIZECONTROL=1; SIZE=$OPTARG;;
    d) DIRECTORY=$OPTARG;;
    *) usage; exit;;
    esac
done

# No options in command line
[ $1 ] || { usage; exit; }

# No -d option in command line
[ "$DIRECTORY" ] ||  { echo "linkdup: the -d option is mandatory."; exit; }

# Directory not found
[ -d "$DIRECTORY" ] || { echo "linkdup: directory $DIRECTORY not found."; exit; }

# Conflict between -s and -S options
COUNTLINK=$(($SYMLINK+$ASYMLINK))
[ $COUNTLINK -gt 1 ] && { echo "linkdup: -s and -S options can not be used at the same time."; exit; }

# Check size
[ $SIZECONTROL = "1" -a -z "$SIZE" ] && { echo "linkdup: you must provide a maximum size in -l option."; exit; }

###############################
### Search for duplicate files
###############################

# Calculate hashes
find $DIRECTORY -type f -maxdepth $MAXDEPTH -exec $HASH {} 2> /dev/null \; > $TMPFILE-list
cat $TMPFILE-list | cut -d" " -f1 | sort | uniq -d > $TMPFILE-duphash

# No results for all methods (-s, -S)
[ -s $TMPFILE-duphash ] || { echo "No duplicate files found."; { [ $MAXDEPTH = "1" ] && echo "Try to use -r."; }; exit; }

# Duplicate files
for DUP in $(cat $TMPFILE-duphash)
do
    SUFFIXH=$(echo $DUP | cut -c -6)
    GROUPFILE=$TMPFILE-dup-$SUFFIXH
    > $GROUPFILE
    cat $TMPFILE-list | grep $DUP >> $GROUPFILE
done


#################
### Ok, let's go!
#################

# If will show files only...
[ $SYMLINK = "0" -a $ASYMLINK = "0" ] && { printf "\nDuplicate files:\n\n" ; }

for FILE in $TMPFILE-dup-*
do
    # Only show files
    [ $SYMLINK = "0" -a $ASYMLINK = "0" ] && { echo "---" ; cat $FILE; }

    # Make relative symlinks
    [ $SYMLINK = "1" ] && { OPTIONS="-sfr"; makelinks; }

    # Make absolute symlinks
    [ $ASYMLINK = "1" ] && { OPTIONS="-sf"; makelinks; }
done


######################
### Removing tmp files
######################

tmpremove
